name: CI/CD - Deploy a EC2

on:
  push:
    branches:
      - main  # Se ejecuta solo cuando hay cambios en la rama "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 游댳 Clonar repositorio
      uses: actions/checkout@v3

    - name: 游댳 Configurar Docker y login en Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: 游댳 Construir im치genes Docker
      run: |
        docker build -t alexismendozaa/evaluaruc-backend:latest -f backend/Dockerfile .
        docker build -t alexismendozaa/evaluaruc-frontend:latest -f frontend/Dockerfile .

    - name: 游댳 Subir im치genes a Docker Hub
      run: |
        docker push alexismendozaa/evaluaruc-backend:latest
        docker push alexismendozaa/evaluaruc-frontend:latest

    - name: 游댳 Configurar conexi칩n SSH y desplegar en EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Moverse al directorio del proyecto
          cd /home/ubuntu/evaluaruc

          # Descargar las nuevas im치genes de Docker Hub
          docker pull alexismendozaa/evaluaruc-backend:latest
          docker pull alexismendozaa/evaluaruc-frontend:latest

          # Borrar contenedores antiguos si existen
          docker-compose down

          # Levantar los nuevos contenedores
          docker-compose up -d
